-- [Break Routine Normalization Script]
-- 기존 'routine_title', 'routine_items' 테이블을 'break_routine_title', 'break_routine_items'로 변경합니다.
-- 방법: 새 테이블 생성 -> 데이터 복사 -> (나중에 기존 테이블 삭제)

-- 1. 쉬는시간 타이틀 테이블 생성
create table if not exists public.break_routine_title (
  id bigint generated by default as identity primary key,
  title text not null default '쉬는시간 루틴',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 쉬는시간 아이템 테이블 생성
create table if not exists public.break_routine_items (
  id uuid default gen_random_uuid() primary key,
  routine_id bigint references public.break_routine_title(id) on delete cascade,
  content text not null, -- 기존 routine_items가 content 컬럼 사용했음
  order_index int4 default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 데이터 마이그레이션
do $$
declare
  r record;
  new_title_id bigint;
begin
  -- 기존 타이틀 데이터 복사
  for r in select * from public.routine_title loop
    insert into public.break_routine_title (title)
    values (r.title)
    returning id into new_title_id;

    -- 해당 타이틀에 속한 아이템 복사
    insert into public.break_routine_items (routine_id, content, order_index)
    select new_title_id, content, order_index
    from public.routine_items
    where routine_id = r.id;
  end loop;
end $$;

-- 4. 확인
-- select * from public.break_routine_title;

-- 5. 기존 테이블 삭제 (나중에 실행하세요)
-- drop table public.routine_items;
-- drop table public.routine_title;
