-- [Attendance Routine Normalization Script]
-- 기존 'routines' 테이블을 'attendance_routine_title'과 'attendance_routine_items'로 분리합니다.

-- 1. 타이틀 테이블 생성
create table if not exists public.attendance_routine_title (
  id bigint generated by default as identity primary key,
  title text not null default '등교시간 루틴',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. 아이템 테이블 생성
create table if not exists public.attendance_routine_items (
  id uuid default gen_random_uuid() primary key,
  title_id bigint references public.attendance_routine_title(id) on delete cascade,
  text text not null,
  order_index int4 default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. 기존 데이터 마이그레이션 (선택 사항)
-- 기존 'routines' 테이블에서 가장 많이 쓰인(혹은 임의의) 제목 하나를 가져와서 타이틀로 생성
-- 데이터가 없으면 '등교시간 루틴' 기본값으로 생성됨
do $$
declare
  new_title_id bigint;
  legacy_title text;
begin
  -- 기존 테이블에 데이터가 있는지 확인 (테이블명이 'routines'라고 가정)
  -- 만약 기존 테이블명이 다르다면 수정 필요
  select distinct routine_title into legacy_title from public.routines limit 1;

  if legacy_title is null then
    legacy_title := '등교시간 루틴';
  end if;

  -- 타이틀 생성
  insert into public.attendance_routine_title (title)
  values (legacy_title)
  returning id into new_title_id;

  -- 기존 아이템 복사 (text 컬럼명이 db에 따라 다를 수 있음, 확인 필요)
  -- 여기서는 기존 컬럼명을 text로 가정. (스크린샷엔 text로 보임)
  insert into public.attendance_routine_items (title_id, text, order_index)
  select new_title_id, text, order_index
  from public.routines
  order by order_index asc;

end $$;

-- 4. 확인 후 기존 테이블 삭제 (나중에 실행하세요)
-- drop table public.routines;
